import { Component } from '@angular/core';

@Component({
  selector: 'app-technicalskills',
  templateUrl: './technicalskills.component.html',
  styleUrls: ['./technicalskills.component.scss'],
})
export class TechnicalskillsComponent {
  skills: any[] = [];

  constructor() {
    this.skills = [
      {
        title: 'programming languages',
        badges: ['JavaScript', 'TypeScript', 'Python', 'Java', 'C#'],
        icons: [
          '../../../../assets/images/skills/js.png',
          '../../../../assets/images/skills/ts.png',
          '../../../../assets/images/skills/py.png',
          '../../../../assets/images/skills/java.png',
          '../../../../assets/images/skills/c-sharp.png',
        ],
      },
      {
        title: 'frontend technologies',
        badges: [
          'angular',
          'ngrx',
          'rxjs',
          'primneg',
          'html',
          'css',
          'sass',
          'bootstrap v5.3',
          'tailwind.css',
          'material ui',
          'jquery',
          'json',
          'xml',
          'es6',
          'jest',
          'highcharts.js',
        ],
        icons: [
          '../../../../assets/images/skills/angular.svg',
          '../../../../assets/images/skills/ngrx.svg',
          '../../../../assets/images/skills/rxjs.svg',
          '../../../../assets/images/skills/primng.svg',
          '../../../../assets/images/skills/html.png',
          '../../../../assets/images/skills/css.png',
          '../../../../assets/images/skills/sass.png',
          '../../../../assets/images/skills/boot.png',
          '../../../../assets/images/skills/tailwind.png',
          '../../../../assets/images/skills/material.png',
          '../../../../assets/images/skills/jquery.png',
          '../../../../assets/images/skills/json.png',
          '../../../../assets/images/skills/xml.png',
          '../../../../assets/images/skills/es6.svg',
          '../../../../assets/images/skills/jest.png',
          '../../../../assets/images/skills/highcharts.svg',
        ],
      },
      {
        title: 'databases',
        badges: ['sql server', 'mysql', 'firebase', 'mongodb', 'sqlite'],
        icons: [
          '../../../../assets/images/skills/sql-server.png',
          '../../../../assets/images/skills/mysql.png',
          '../../../../assets/images/skills/firebase.png',
          '../../../../assets/images/skills/mongo.png',
          '../../../../assets/images/skills/sqlite.png',
        ],
      },
      {
        title: 'tools & ide',
        badges: [
          'npm',
          'figma',
          'adobe xd',
          'draw.io',
          'postman',
          'swagger',
          'vs code',
          'visual studio',
          'trello',
        ],
        icons: [
          '../../../../assets/images/skills/npm.png',
          '../../../../assets/images/skills/figma.png',
          '../../../../assets/images/skills/xd.png',
          '../../../../assets/images/skills/draw-io.svg',
          '../../../../assets/images/skills/postmat.png',
          '../../../../assets/images/skills/swagger.png',
          '../../../../assets/images/skills/vs-code.png',
          '../../../../assets/images/skills/vs.png',
          '../../../../assets/images/skills/trello.png',
        ],
      },
      {
        title: 'version control',
        badges: [
          'git',
          'source tree',
          'github',
          'gitlab',
          'vercel',
          'netlify',
          'bitbucket',
        ],
        icons: [
          '../../../../assets/images/skills/git.png',
          '../../../../assets/images/skills/sourcetree-seeklogo.svg',
          '../../../../assets/images/skills/github.png',
          '../../../../assets/images/skills/gitlab.png',
          '../../../../assets/images/skills/vercel.png',
          '../../../../assets/images/skills/netlify.png',
          '../../../../assets/images/skills/bitbucket.png',
        ],
      },
      {
        title: 'other',
        badges: [
          'restful apis',
          'agile',
          'unit testing',
          'signals',
          'state management',
          'media query',
          'responsive design',
          'ajax',
          'dom',
          'promise',
          'xmlhttp',
          'async/await',
          'fetch api',
          'local storage',
          'session storage',
          'web components',
        ],
        icons: [],
      },
    ];
  }
}
